### ISSUE TITLE
Crash the server on startup

### ISSUE THREAD

**Issue by Prull99** [Source2ZE/MovementUnlocker#2]
No error logs.

**Comment by pimpmyname2** [comment]
Yea can agree on that too. (cs2 28-02 update caused this)

**Comment by Dliix66** [comment]
I can confirm, nothing interesting in the logs:
![image](https://github.com/Source2ZE/MovementUnlocker/assets/2865871/457ae1fa-7eda-4a23-9de4-dbd43e26ab62)

**Comment by Vauff** [comment]
Resolved by https://github.com/Source2ZE/MovementUnlocker/commit/5ff589cf87285218c5941e2987ec3aeefd3fd8da.
