### ISSUE TITLE
Server crashes on startup since new CS2-Update 4/2/2024. 

### ISSUE THREAD

**Issue by Sacricx** [Source2ZE/MovementUnlocker#3]

**Comment by Sacricx** [comment]
Please update the signature, thanks a lot!

**Comment by Sacricx** [comment]
@

**Comment by Vauff** [comment]
Fixed in https://github.com/Source2ZE/MovementUnlocker/commit/07efcaab9bfe1af1b6b3f05b3abe8fd35319e73e, sorry for the delay, I was very sick at the time the update happened, and forgot afterwards due to Linux not being affected.
