### ISSUE TITLE
Need to update

### ISSUE THREAD

**Issue by pump4love** [Source2ZE/MovementUnlocker#7]
After cs2 update please 
Release 10/2/2024

**Comment by oylsister** [comment]
``[META] Failed to load plugin addons/MovementUnlocker/bin/linuxsteamrt64/MovementUnlocker: /home/cs2server/serverfiles/game/csgo/addons/MovementUnlocker/bin/linuxsteamrt64/MovementUnlocker.so: undefined symbol: _AssertValidWritePtr``

**Comment by oylsister** [comment]
trigger workflow it will compile with latest sdk change. https://github.com/oylsister/MovementUnlocker/actions/runs/11191273662

**Comment by Vauff** [comment]
[v1.4](https://github.com/Source2ZE/MovementUnlocker/releases/tag/v1.4) is now released to fix this.

> trigger workflow it will compile with latest sdk change. https://github.com/oylsister/MovementUnlocker/actions/runs/11191273662

The Windows signature also broke.
