### ISSUE TITLE
Shift Walk Mode Increased Speed

### ISSUE THREAD

**Issue by shizangle** [Source2ZE/MovementUnlocker#9]
When using shift-walk, player speed exceeds what should normally be possible. 

Testing with sv_accelerate 10
**without shift+walk**: 352 max with or without weapon.
with weapon: max ground run speed ~370
without weapon: max ground run speed ~390

I'm also using SharpTimer:
sharptimer_forced_player_speed : 260

**Comment by Vauff** [comment]
Cannot reproduce using `sv_accelerate 10` with Movement Unlocker.

If this is something triggered by something SharpTimer does, you're probably better off trying to fix the issue there. The only thing this plugin does is skip an `if` check in game code, so player ground speed is not clamped to max speed. Thus, there's not really room to do anything else, if you'd rather the check not be skipped, you should just remove the plugin.
